deleteUser method
Tour-App/tour-app-api pull request #3
Opened 2022-05-11 02:30 UTC by belemzzuka

Added deleteUser method.
Destroy method response is the number of rows destroyed. Therefore, error validation is made after the promise, not in the catch.

2022-05-11 02:40 UTC, YannYiss approved these changes

2022-05-11 02:40 UTC, yaravi approved these changes

2022-05-11 06:43 UTC, RocioChamorro approved these changes

2022-05-11 14:45 UTC, MisaelCalvillo requested changes

2022-05-11 14:45 UTC, MisaelCalvillo commented on server/controllers/userController.js
> +  if (deletedUser === 1) {
Aquí @belemzzuka sugeriría que utilicemos alguna estructura diferente de como estamos validando este código. Por ejemplo, aquí, primero estas validando la opción esperada (si es 1 regresa `Usuarios borrado exitosamente`). Y luego de eso validas si es 0 regresas `El usuario que intentas borrar no existe`. 

La lógica esta bien, pero yo acomodaría el código de una forma un poquito distinta. Por varias razones. 
```js
  if (!deletedUser) {
   return res.status(402).json({ message: "El usuario que intentas borrar, no existe" });
  }
  
  return res.status(200).json({message: "Usuario borrado exitosamente"})
```

Con esto reducimos la cantidad de código y pasos lógicos que hay que realizar. Digamos estamos haciendo un proceso "optimista" que espera que el paso final fue que todo salió bien. Por ende si llegamos a la linea donde nos da un mensaje de éxito, todo estuvo correcto y ese siempre debería ser el final del proceso.

2022-05-11 16:49 UTC, belemzzuka commented on server/controllers/userController.js
> +  if (deletedUser === 1) {
Gracias por la recomendación. Cambios aplicados.

2022-05-11 19:41 UTC, Stepalom77 approved these changes

2022-05-11 23:36 UTC, jcvillacorta approved these changes

2022-05-11 23:53 UTC, MisaelCalvillo requested changes

2022-05-11 23:53 UTC, MisaelCalvillo commented on server/controllers/userController.js
>    // TODO 3 -Borrar información del usuario (Belem)
No vi esto pero hay que quitar el TODO @belemzzuka

2022-05-11 23:55 UTC, belemzzuka commented on server/controllers/userController.js
>    // TODO 3 -Borrar información del usuario (Belem)
Done

2022-05-12 00:01 UTC, MisaelCalvillo approved these changes

2022-05-12 00:03 UTC, merged