City controller
Tour-App/tour-app-api pull request #4
Opened 2022-05-11 02:32 UTC by Stepalom77

2022-05-11 02:45 UTC, belemzzuka commented on server/controllers/cityController.js
> +const getCity = async (req, res) => {
Falta el código de obtener una sola ciudad?

2022-05-11 02:45 UTC, belemzzuka commented on server/controllers/cityController.js
> +
Falta el código para actualizar ciudad

2022-05-11 02:45 UTC, belemzzuka commented on server/controllers/cityController.js
> +
Falta el código para borrar una ciudad. Puedes usar el mío de borrar usuario, ya está listo 😄

2022-05-11 14:34 UTC, MisaelCalvillo commented on server/controllers/cityController.js
> +const getCity = async (req, res) => {
Misma duda con el código de obtener una sola ciudad. Igual si tú tienes una propuesta para eso @belemzzuka, podrías subir alguna sugerencia en la forma de un commit. Solo acordemos eso en este chat antes de arrancar.

2022-05-11 14:35 UTC, MisaelCalvillo commented on server/controllers/cityController.js
> +  console.log(req.body);
Este `console.log` no se te olvide quitarlo.

2022-05-11 14:37 UTC, MisaelCalvillo requested changes
Faltan algunas cosas @Stepalom77

2022-05-11 14:37 UTC, MisaelCalvillo commented on server/controllers/cityController.js
> +
Misma duda con el código para actualizar la ciudad. No olvides eso @Stepalom77

2022-05-11 14:37 UTC, MisaelCalvillo commented on server/controllers/cityController.js
> +
Misma observación !

2022-05-11 17:02 UTC, belemzzuka commented on server/controllers/cityController.js
> +
Ya veo los cambios, gracias!

2022-05-11 17:03 UTC, belemzzuka commented on server/controllers/cityController.js
> +
Ya veo los cambios, gracias

2022-05-11 17:03 UTC, belemzzuka commented on server/controllers/cityController.js
> +const getCity = async (req, res) => {
Ya veo los cambios, gracias

2022-05-11 17:03 UTC, belemzzuka approved these changes

2022-05-11 17:31 UTC, YannYiss approved these changes
Looking good!

2022-05-12 00:04 UTC, MisaelCalvillo approved these changes
Solo tengo una duda.

2022-05-12 00:04 UTC, MisaelCalvillo commented on server/controllers/cityController.js
> +//getCities
Creo que quitaría estos comentarios arriba de las funciones @Stepalom77

2022-05-12 00:20 UTC, jcvillacorta approved these changes

2022-05-12 00:56 UTC, AdnerbImohan1107 requested changes

2022-05-12 00:56 UTC, AdnerbImohan1107 commented on server/controllers/cityController.js
> +  let cityToUpdate = await city.findByPk(cityId)
Esta linea deberia deberia de estar dentro de un try catch

2022-05-12 01:06 UTC, MisaelCalvillo approved these changes
Todo parece estar bien !

2022-05-12 01:13 UTC, Luiroja approved these changes

2022-05-12 01:19 UTC, octenrique approved these changes
correcto

2022-05-12 01:20 UTC, MisaelCalvillo approved these changes

2022-05-12 01:21 UTC, Yauris12 approved these changes

2022-05-12 01:22 UTC, Stepalom77 commented on server/controllers/cityController.js
> +  let cityToUpdate = await city.findByPk(cityId)
Listo

2022-05-12 01:22 UTC, AdnerbImohan1107 approved these changes

2022-05-12 01:22 UTC, merged