Places CRUD
Tour-App/tour-app-api pull request #5
Opened 2022-05-11 03:43 UTC by AdnerbImohan1107

2022-05-11 14:59 UTC, MisaelCalvillo requested changes
@AdnerbImohan1107 te dejo comentarios sobre algunas cosas que noté. Solo es eso. En realidad todo el CRUD se ve bien.

2022-05-11 14:59 UTC, MisaelCalvillo commented on server/controllers/placesController.js
> +    return res.status(200).json({
Aquí en el caso del update, sería buena idea que regresaras el lugar ya actualizado, en lugar de solamente el mensaje.

2022-05-11 14:59 UTC, MisaelCalvillo commented on server/controllers/placesController.js
> +  if (!id) {
Aquí más bien, no es un if que valida si el lugar lo encontró o no. En realidad lo que estas validando aquí es si el usuario mandó el `id` o no. Por lo que el paso para validar si existe o no un `place` con este id no va aquí.

2022-05-11 14:59 UTC, MisaelCalvillo commented on server/controllers/placesController.js
> +    return res.status(200).json({
Justo como lo haces en el controller `createPlace` en la linea 40

2022-05-11 14:59 UTC, MisaelCalvillo commented on server/controllers/placesController.js
> +      message: "Lugar no encontrado",
Mismo tema con el mensaje. Aquí no significa que el lugar no fue encontrado, sino que no pasó un `id`.

2022-05-11 17:57 UTC, AdnerbImohan1107 commented on server/controllers/placesController.js
> +    return res.status(200).json({
Resuelto

2022-05-11 17:59 UTC, AdnerbImohan1107 commented on server/controllers/placesController.js
> +  if (!id) {
¿Como podria validar si existe o no el id?  ya que cuando no se ingresa el id en la ruta no ingresa al método.

2022-05-12 00:11 UTC, belemzzuka approved these changes

2022-05-12 01:04 UTC, MisaelCalvillo approved these changes
Todo se ve bien. @AdnerbImohan1107

2022-05-12 01:04 UTC, MisaelCalvillo requested changes

2022-05-12 01:04 UTC, MisaelCalvillo commented on server/routes/index.js
> +router.patch("/places/:id", place.update);
Aquí ya solo sería usar `post`.

2022-05-12 01:08 UTC, YannYiss requested changes
Faltó indicar el request en los parametros de la funcion getPlaces

2022-05-12 01:08 UTC, YannYiss commented on server/controllers/placesController.js
> +const getPlaces = async (_, res) => {
falta especificar el request

2022-05-12 01:09 UTC, AdnerbImohan1107 commented on server/controllers/placesController.js
> +const getPlaces = async (_, res) => {
El request no se utiliza en este metodo, por tanto es opcional ponerlo

2022-05-12 01:12 UTC, MisaelCalvillo approved these changes

2022-05-12 01:12 UTC, RocioChamorro approved these changes

2022-05-12 01:13 UTC, YannYiss approved these changes

2022-05-12 01:15 UTC, Luiroja approved these changes

2022-05-12 01:17 UTC, jcvillacorta approved these changes

2022-05-12 01:17 UTC, Stepalom77 approved these changes

2022-05-12 01:17 UTC, Stepalom77 commented on server/controllers/placesController.js
> +    const placeUpdated = await place.update(req.body, {
No estoy seguro si el req.body sirve ahí, según la documentación de sequelize en update tienes que colocar cada columna junto a su nuevo valor todo en un objeto. Podrías destructurar req.body en cada columna correspondiente y luego colocarlo en update. Checa mi código.

2022-05-12 01:17 UTC, Stepalom77 commented on server/controllers/placesController.js
>        where: {
Debes asignarle al id el valor del id del request:
```suggestion
      where: {
      id: id
      }
```

2022-05-12 01:19 UTC, RocioChamorro approved these changes

2022-05-12 01:24 UTC, merged

2022-05-12 01:24 UTC, Yauris12 approved these changes