Rocio/updateUser
Tour-App/tour-app-api pull request #6
Opened 2022-05-11 06:39 UTC by RocioChamorro

2022-05-11 15:20 UTC, MisaelCalvillo requested changes
Todo se ve bastante bien. @RocioChamorro 

Solo te dejé unos comentarios.

2022-05-11 15:20 UTC, MisaelCalvillo commented on server/controllers/userController.js
> +      res.status(400)
Aquí hace falta un return. De lo contrario el proceso va a pasar a la siguientes lineas. Cuando mandas la respuesta y aún hay líneas a ejecutar después se van a ejecutar. 

```suggestion
     return res.status(400)
```

2022-05-11 15:20 UTC, MisaelCalvillo commented on server/controllers/userController.js
> +      throw new Error('Tarea no encontrada');
Este error va a tirar todo el backend y no es la idea. Es mejor que mantengamos el error controlado y no dejemos que escale hasta tirar todo.

2022-05-11 15:20 UTC, MisaelCalvillo commented on server/controllers/userController.js
> +  try {
El `try { } catch() {}` solamente debe usarse para cuando estamos haciendo alguna llamada a un recurso externo como en este caso es la llamada a la base de datos. No es tan buena idea meter todo dentro del try porque de haber un error no te vas a dar cuenta.

2022-05-11 15:20 UTC, MisaelCalvillo commented on server/controllers/userController.js
> +      selectedUser.first_name = first_name;
Esta forma de manejar los valores esta bien, pero es un poco repetitiva, podrías usar `selectedUser.update()`. Esto es una mera sugerencia. El código esta bien y funciona, solo más adelante validamos cual de las diferentes formas de hacerlo es mejor.

2022-05-11 15:20 UTC, MisaelCalvillo commented on server/controllers/userController.js
> +      res.json(selectedUser);
Es buena práctica que agregues el return siempre antes de mandar las respuestas. Reduces la posibilidad de un error porque el proceso siguió ejecutándose. 

```suggestion
      return res.json(selectedUser);
```

2022-05-12 00:02 UTC, Yauris12 approved these changes

2022-05-12 00:09 UTC, belemzzuka requested changes

2022-05-12 00:09 UTC, belemzzuka commented on server/controllers/userController.js
> -  // TODO 2 - Actualizar información del usuario (Rocio)
Borrar la instrucción TODO

2022-05-12 00:14 UTC, octenrique approved these changes
Cambios correctos

2022-05-12 00:22 UTC, belemzzuka approved these changes

2022-05-12 00:54 UTC, MisaelCalvillo approved these changes

2022-05-12 00:55 UTC, yaravi approved these changes

2022-05-12 00:55 UTC, Yauris12 approved these changes

2022-05-12 00:55 UTC, Stepalom77 approved these changes

2022-05-12 00:57 UTC, YannYiss approved these changes
looking good!

2022-05-12 01:05 UTC, merged