Luis
Tour-App/tour-app-api pull request #7
Opened 2022-05-11 16:44 UTC by Luiroja

Pull request del TODO-4  "Obtener información de un solo usuario"

2022-05-11 23:58 UTC, jcvillacorta approved these changes

2022-05-12 00:01 UTC, YannYiss reviewed
Solo faltaria remover el ToDo

2022-05-12 00:01 UTC, YannYiss commented on server/controllers/userController.js
> +  // TODO 4 - Obten la información de un solo usuario
Se pudiera remover la instrucción del ToDo

2022-05-12 00:05 UTC, Yauris12 approved these changes

2022-05-12 00:05 UTC, Stepalom77 approved these changes

2022-05-12 00:07 UTC, Luiroja commented on server/controllers/userController.js
> +  // TODO 4 - Obten la información de un solo usuario
ok, ahora remuevo eso

2022-05-12 00:11 UTC, MisaelCalvillo requested changes
Todo bien, quizá puedes mejorar como respondes cuando no hay un id.

2022-05-12 00:11 UTC, MisaelCalvillo commented on server/controllers/userController.js
> +  // TODO 4 - Obten la información de un solo usuario
Hay que quitar el comentario @Luiroja

2022-05-12 00:11 UTC, octenrique approved these changes
a mi parecer, el código funciona

2022-05-12 00:14 UTC, YannYiss approved these changes

2022-05-12 00:18 UTC, Luiroja reviewed
eliminando el comentario TODO

2022-05-12 00:20 UTC, Luiroja commented on server/controllers/userController.js
> +  // TODO 4 - Obten la información de un solo usuario
ya hice eso @MisaelCalvillo

2022-05-12 00:24 UTC, belemzzuka approved these changes

2022-05-12 01:01 UTC, MisaelCalvillo approved these changes

2022-05-12 01:06 UTC, Luiroja reviewed
Manejando el error cuando el ID buscado en la API no existe

2022-05-12 01:07 UTC, RocioChamorro approved these changes

2022-05-12 01:12 UTC, merged